=== dsapandora/DSACharacterMaker/resources/schema/0.8/character.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  targetNamespace="http://com.exmaple/charactermanaj"
  xmlns="http://com.exmaple/charactermanaj"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xml="http://www.w3.org/XML/1998/namespace"
  attributeFormDefault="qualified"
  elementFormDefault="qualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
  <xs:include schemaLocation="character_inc.xsd"/>
  <xs:element name="character">
    <xs:annotation>
      <xs:documentation xml:lang="ja">キャラクターデータの定義</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" nillable="false" minOccurs="1" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation xml:lang="ja">キャラクターデータ名。該当するlangがなければ最初の定義をデフォルト値とする。</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="tokenNotEmpty">
                 <xs:attribute ref="xml:lang" use="required" />
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="information" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="ja">備考</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" minOccurs="0" maxOccurs="unbounded" nillable="false">
                <xs:annotation>
                  <xs:documentation xml:lang="ja">作者名</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xml:lang" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="description" minOccurs="1" maxOccurs="unbounded" nillable="false">
                <xs:annotation>
                  <xs:documentation xml:lang="ja">説明文</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute ref="xml:lang" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="image-size">
          <xs:annotation>
            <xs:documentation xml:lang="ja">イメージのサイズ(幅と高さ)</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="width">
                <xs:simpleType>
                  <xs:restriction base="xs:unsignedInt">
                    <xs:minExclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="height">
                <xs:simpleType>
                  <xs:restriction base="xs:unsignedInt">
                    <xs:minExclusive value="0"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="settings" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="ja">雑多なプロパティのコレクション</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation xml:lang="ja">雑多なプロパティ</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="key" form="unqualified" use="required" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <xs:element name="categories">
          <xs:annotation>
            <xs:documentation xml:lang="ja">カテゴリの定義リスト、出現順で画面に表示される。</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="category" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation xml:lang="ja">カテゴリの定義</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="visible-rows" nillable="false" type="xs:positiveInteger">
                      <xs:annotation>
                        <xs:documentation xml:lang="ja">表示するパーツの行数(初期値)</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element name="display-name" nillable="false" minOccurs="1" maxOccurs="unbounded">
                      <xs:annotation>
                        <xs:documentation xml:lang="ja">カテゴリの表示名、該当するlangがない場合は最初のものをデフォルトとする。</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="tokenNotEmpty">
                            <xs:attribute ref="xml:lang" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="layers">
                      <xs:annotation>
                        <xs:documentation xml:lang="ja">パーツを構成するレイヤーの定義リスト</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="layer" minOccurs="1" maxOccurs="unbounded">
                            <xs:annotation>
                              <xs:documentation xml:lang="ja">パーツを構成するレイヤーの定義</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="display-name" nillable="false" minOccurs="1" maxOccurs="unbounded">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ja">レイヤーの表示名、該当するlangがない場合は最初のものをデフォルトとする。</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="tokenNotEmpty">
                                        <xs:attribute ref="xml:lang" use="required"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="order" nillable="false" type="xs:integer">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ja">パーツ全体でレイヤーを重ね合わせる順序。</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element name="colorGroup" minOccurs="0" maxOccurs="1">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ja">色設定を連動させるグループの指定(省略可)</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:attribute name="refid" form="unqualified" type="tokenNotEmpty" use="required">
                                      <xs:annotation>
                                        <xs:documentation xml:lang="ja">カラーグループID</xs:documentation>
                                      </xs:annotation>
                                    </xs:attribute>
                                    <xs:attribute name="init-sync" form="unqualified" use="required">
                                      <xs:annotation>
                                        <xs:documentation xml:lang="ja">初期状態で連動させるか?</xs:documentation>
                                      </xs:annotation>
                                      <xs:simpleType>
                                        <xs:restriction base="xs:boolean">
                                          <xs:pattern value="true"/>
                                          <xs:pattern value="false"/>
                                        </xs:restriction>
                                      </xs:simpleType>
                                    </xs:attribute>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="dir" nillable="false" type="tokenNotEmpty">
                                  <xs:annotation>
                                    <xs:documentation xml:lang="ja">このレイヤーの画像を格納しているディレクトリ名</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="id" form="unqualified" type="tokenNotEmpty" use="required">
                                <xs:annotation>
                                  <xs:documentation xml:lang="ja">レイヤーの識別子</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" form="unqualified" type="tokenNotEmpty" use="required">
                    <xs:annotation>
                      <xs:documentation xml:lang="ja">カテゴリーの識別子</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="multipleSelectable" form="unqualified" use="required">
                    <xs:annotation>
                      <xs:documentation xml:lang="ja">このカテゴリで複数のパーツが選択可能であるか?</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                      <xs:restriction base="xs:boolean">
                        <xs:pattern value="true"/>
                        <xs:pattern value="false"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="colorGroups" minOccurs="0" maxOccurs="1">
          <xs:annotation>
            <xs:documentation xml:lang="ja">カラーグループの定義リスト</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="colorGroup" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation xml:lang="ja">カラーグループの定義</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="display-name" nillable="false" minOccurs="1" maxOccurs="unbounded">
                      <xs:annotation>
                        <xs:documentation xml:lang="ja">カラーグループの表示名。該当するlangがない場合は最初をデフォルトとする。</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="tokenNotEmpty">
                            <xs:attribute ref="xml:lang" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" form="unqualified" type="tokenNotEmpty" use="required">
                    <xs:annotation>
                      <xs:documentation xml:lang="ja">カラーグループの識別子</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="presets" minOccurs="0" maxOccurs="1" type="presetsType">
          <xs:annotation>
            <xs:documentation xml:lang="ja">定義済みパーツ組み合わせ例(プリセット)の定義リスト、定義順に表示される。</xs:documentation>
          </xs:annotation>
		</xs:element>

      </xs:sequence>
      <xs:attribute name="id" form="unqualified" type="tokenNotEmpty" use="required"/>
      <xs:attribute name="rev" form="unqualified" type="tokenNotEmpty" use="required"/>
      <xs:attribute name="version" form="unqualified" type="tokenNotEmpty" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="ja">このXMLのバージョン番号、1.0固定。</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>

    <xs:key name="category-id">
      <xs:selector xpath="categories/category"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="layer-id">
      <xs:selector xpath="categories/category/layers/layer"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:key name="colorGroup-id">
      <xs:selector xpath="colorGroups/colorGroup"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
</xs:schema>

=== dsapandora/DSACharacterMaker/resources/template/character3.xml
<?xml version="1.0"?>
<character
    xmlns="http://charactermanaj.sourceforge.jp/schema/charactermanaj"
    xmlns:xml="http://www.w3.org/XML/1998/namespace"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://charactermanaj.sourceforge.jp/schema/charactermanaj character.xsd"
    version="1.0"
    id="default"
    rev="default_v3">

    <name xml:lang="en">Default(v3)</name>
    <name xml:lang="ja">デフォルト(v3)</name>

    <information>
    	<author xml:lang="en">Unknown</author>
    	<author xml:lang="ja">名無し</author>
        <author xml:lang="zh">无名</author>
        <author xml:lang="zh_TW">無名</author>
    	<description xml:lang="en"><![CDATA[default character]]></description>
    	<description xml:lang="ja"><![CDATA[デフォルトのキャラクター(キャラクターなんとか機Ver3互換セット)]]></description>
    </information>

    <image-size>
        <width>300</width>
        <height>400</height>
    </image-size>

    <settings>
        <entry key="watch-dir">true</entry>
    </settings>

    <categories>
        <category id="hair_front" multipleSelectable="false">
            <visible-rows>6</visible-rows>
            <display-name xml:lang="en">Hair - Front</display-name>
            <display-name xml:lang="ja">髪型 - 手前</display-name>
            <display-name xml:lang="zh">发型 - 这边</display-name>
            <display-name xml:lang="zh_TW">髮型 - 這邊</display-name>
            <layers>
                <layer id="hair_front">
                    <display-name xml:lang="en">Variable</display-name>
                    <display-name xml:lang="ja">可変色</display-name>
                    <display-name xml:lang="zh">可变颜色</display-name>
                    <display-name xml:lang="zh_TW">可變顏色</display-name>
                    <order>13</order>
                    <colorGroup refid="color-hair" init-sync="true"/>
                    <dir>hair_front</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="hair_front_accessory">
                    <display-name xml:lang="en">Accessory</display-name>
                    <display-name xml:lang="ja">アクセサリ</display-name>
                    <display-name xml:lang="zh">饰品</display-name>
                    <display-name xml:lang="zh_TW">飾品</display-name>
                    <order>14</order>
                    <dir>hair_front_accessory</dir>
                    <colorModel>HSB</colorModel>
                </layer>
            </layers>
        </category>
        <category id="hair_back" multipleSelectable="false">
            <visible-rows>6</visible-rows>
            <display-name xml:lang="en">Hair - Back</display-name>
            <display-name xml:lang="ja">髪型 - 後ろ</display-name>
            <display-name xml:lang="zh">发型 - 背后</display-name>
            <display-name xml:lang="zh_TW">髮型 - 背後</display-name>
            <layers>
                <layer id="hair_back">
                    <display-name xml:lang="en">Variable</display-name>
                    <display-name xml:lang="ja">可変色</display-name>
                    <display-name xml:lang="zh">可变颜色</display-name>
                    <display-name xml:lang="zh_TW">可變顏色</display-name>
                    <order>2</order>
                    <colorGroup refid="color-hair" init-sync="true"/>
                    <dir>hair_back</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="hair_back_accessory">
                    <display-name xml:lang="en">Accessory</display-name>
                    <display-name xml:lang="ja">アクセサリ</display-name>
                    <display-name xml:lang="zh">饰品</display-name>
                    <display-name xml:lang="zh_TW">飾品</display-name>
                    <order>3</order>
                    <dir>hair_back_accessory</dir>
                    <colorModel>HSB</colorModel>
                </layer>
            </layers>
        </category>
        <category id="head" multipleSelectable="false">
            <visible-rows>6</visible-rows>
            <display-name xml:lang="en">Head</display-name>
            <display-name xml:lang="ja">頭</display-name>
            <display-name xml:lang="zh">头</display-name>
            <display-name xml:lang="zh_TW">頭</display-name>
            <layers>
                <layer id="head">
                    <display-name xml:lang="en">Head</display-name>
                    <display-name xml:lang="ja">頭</display-name>
                    <display-name xml:lang="zh">头</display-name>
                    <display-name xml:lang="zh_TW">頭</display-name>
                    <order>10</order>
                    <colorGroup refid="color-skin" init-sync="true"/>
                    <dir>head</dir>
                    <colorModel>HSB</colorModel>
                </layer>
            </layers>
        </category>
        <category id="face" multipleSelectable="false">
            <visible-rows>6</visible-rows>
            <display-name xml:lang="en">Expression</display-name>
            <display-name xml:lang="ja">表情</display-name>
            <display-name xml:lang="zh">脸色</display-name>
            <display-name xml:lang="zh_TW">臉色</display-name>
            <layers>
                <layer id="face_front">    
                    <display-name xml:lang="en">Face</display-name>
                    <display-name xml:lang="ja">表情</display-name>
                    <display-name xml:lang="zh">脸色</display-name>
                    <display-name xml:lang="zh_TW">臉色</display-name>
                    <order>15</order>
                    <dir>face_front</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="face_back">
                    <display-name xml:lang="en">Accessory</display-name>
                    <display-name xml:lang="ja">アクセサリ</display-name>
                    <display-name xml:lang="zh">饰品</display-name>
                    <display-name xml:lang="zh_TW">飾品</display-name>
                    <order>12</order>
                    <dir>face_back</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="face_haircolor">
                    <display-name xml:lang="en">Hair</display-name>
                    <display-name xml:lang="ja">髪色</display-name>
                    <display-name xml:lang="zh">头发颜色</display-name>
                    <display-name xml:lang="zh_TW">頭髮顏色</display-name>
                    <order>16</order>
                    <colorGroup refid="color-hair" init-sync="true"/>
                    <dir>face_haircolor</dir>
                    <colorModel>HSB</colorModel>
                </layer>
            </layers>
        </category>
        <category id="eye" multipleSelectable="false">
            <visible-rows>6</visible-rows>
            <display-name xml:lang="en">Eyes</display-name>
            <display-name xml:lang="ja">目</display-name>
            <display-name xml:lang="zh">眼</display-name>
            <display-name xml:lang="zh_TW">眼</display-name>
            <layers>
                <layer id="eye">
                    <display-name xml:lang="en">Eye</display-name>
                    <display-name xml:lang="ja">目</display-name>
                    <display-name xml:lang="zh">眼</display-name>
                    <display-name xml:lang="zh_TW">眼</display-name>
                    <order>17</order>
                    <dir>eye</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="eye_color">
                    <display-name xml:lang="en">Variable</display-name>
                    <display-name xml:lang="ja">可変色</display-name>
                    <display-name xml:lang="zh">可变颜色</display-name>
                    <display-name xml:lang="zh_TW">可變顏色</display-name>
                    <order>18</order>
                    <colorGroup refid="color-eye" init-sync="true"/>
                    <dir>eye_color</dir>
                    <colorModel>HSB</colorModel>
                </layer>
            </layers>
        </category>
        <category id="body" multipleSelectable="false">
            <visible-rows>6</visible-rows>
            <display-name xml:lang="en">Body</display-name>
            <display-name xml:lang="ja">身体</display-name>
            <display-name xml:lang="zh">身体</display-name>
            <display-name xml:lang="zh_TW">身體</display-name>
            <layers>
                <layer id="body_front_color">
                    <display-name xml:lang="en">Variable</display-name>
                    <display-name xml:lang="ja">可変色</display-name>
                    <display-name xml:lang="zh">可变颜色</display-name>
                    <display-name xml:lang="zh_TW">可變顏色</display-name>
                    <order>7</order>
                    <colorGroup init-sync="true" refid="color-dress"/>
                    <dir>body_front_color</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="body_front">
                    <display-name xml:lang="en">Clothes</display-name>
                    <display-name xml:lang="ja">ドレス</display-name>
                    <display-name xml:lang="zh">衣服</display-name>
                    <display-name xml:lang="zh_TW">衣服</display-name>
                    <order>6</order>
                    <dir>body_front</dir>
                    <colorModel>HSB</colorModel>
                </layer>
                <layer id="body_back">
                    <display-name xml:lang="en">Skin</display-name>
                    <display-name xml:lang="ja">肌</display-name>
                    <display-name xml:lang="zh">皮肤</display-name>
                    <display-name xml:lang="zh_TW">皮膚</display-name>
